<?php

return [
    'BRIGHTCALL_SOURCE_ID' => 3,
    'FACEBOOK_SOURCE_ID' => "2|FACEBOOK",
    'CALL_COLLECTION_SOURCE_ID' => 595,
    'FACEBOOK_COLLECTION_SOURCE_ID' => 587,
    'DEFAULT_RESPONSIBLE_PERSON_ID' => 53, // Masroor Khan
];
